# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# output directory, generated dynamically on each run
# Format: timestamp_experiment (e.g., 2025-12-18_03-41-00_wah_cnn_tiny_regression)
run:
  dir: ${paths.log_dir}/${task_name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}_${oc.select:hydra.runtime.choices.experiment,quick}
sweep:
  dir: ${paths.log_dir}/${task_name}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}_${oc.select:hydra.runtime.choices.experiment,sweep}
  subdir: ${hydra.job.num}

job_logging:
  handlers:
    file:
      # Incorporates fix from https://github.com/facebookresearch/hydra/pull/2242
      filename: ${hydra.runtime.output_dir}/${task_name}.log
