# Small CNN with ~8K parameters for trivial datasets
_target_: src.models.vimh_lit_module.VIMHLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.003
  weight_decay: 0.001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 5

# Pure regression mode with sigmoid-activated outputs
output_mode: regression

# Criteria and loss_weights will be auto-configured from dataset metadata
loss_weights: {}  # Will be auto-configured from dataset metadata

net:
  _target_: src.models.components.simple_cnn.SimpleCNN
  input_channels: 1
  conv1_channels: 16
  conv2_channels: 32
  fc_hidden: 64
  heads_config: 
    synth_param1: 10
  dropout: 0.3
  input_size: 32

compile: false

# Auto-configure heads and parameter ranges from dataset metadata
auto_configure_from_dataset: true
