_target_: src.models.multihead_module.MultiheadLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

# Different criterion per head (will be auto-configured based on dataset)
# For VIMH STK dataset with 1 parameter
criteria:
  note_number:
    _target_: torch.nn.CrossEntropyLoss

# Loss weighting (equal weight to all heads by default)
loss_weights:
  note_number: 1.0

net:
  _target_: src.models.components.simple_cnn.SimpleCNN
  input_channels: 3  # VIMH typically has 3 color channels for spectrograms
  conv1_channels: 64
  conv2_channels: 128
  fc_hidden: 512
  heads_config:
    note_number: 256  # Default - will be overridden by dataset
  dropout: 0.5
  input_size: 32  # VIMH image size (32x32 for spectrograms)

compile: false

# Auto-configure heads from dataset metadata
auto_configure_from_dataset: true
