_target_: src.models.multihead_module.MultiheadLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

# Pure regression mode with sigmoid-activated outputs
output_mode: regression

# Criteria and loss_weights will be auto-configured from dataset metadata
loss_weights: {}  # Will be auto-configured from dataset metadata

net:
  _target_: src.models.components.simple_cnn.SimpleCNN
  input_channels: 3  # VIMH typically has 3 color channels for spectrograms
  conv1_channels: 64
  conv2_channels: 128
  fc_hidden: 512
  output_mode: regression  # Enable regression mode
  parameter_names: [synth_param1]  # Default placeholder - will be auto-configured from dataset metadata
  # parameter_ranges will be auto-configured from dataset metadata
  dropout: 0.5
  input_size: 32  # VIMH image size (32x32 for spectrograms)

compile: false

# Auto-configure heads and parameter ranges from dataset metadata
auto_configure_from_dataset: true
