# @package _global_
# Basic Moog VCF testing configuration

# Dataset parameters
dataset:
  size: 256 # Number of samples to generate
  sampling_rate: 8000 # Sample rate in Hz
  duration: 1.0 # Duration per sample in seconds

# Generation parameters
generate:
  batch_size: 8 # Processing batch size
  output_dir: "data" # Base output directory
  pre_emphasis_coefficient: 0.0 # Pre-emphasis filter coefficient (disabled for flat spectrum test)
  taper: false # Taper breath pressure at note ends
  threshold_db: -40 # Audio threshold in dB

  # Output image dimensions
  height: 32 # Spectrogram height (mel bins)
  width: 32 # Spectrogram width (time bins)
  channels: 1 # Number of channels (1=grayscale, 3=RGB for derived channels)

# Synthesizer configuration
synthesizer:
  type: simple_saw

  # Parameters that can vary during dataset generation
  parameters:
    # MIDI note number (0-127) - FIXED for consistency
    note_number:
      min_value: 43.350 # 100 Hz - exactly 80 samples per cycle at 8000 Hz
      max_value: 43.350
      default: 43.350
      description: "MIDI note number (fixed at 100 Hz)"

    # MIDI velocity (0-127, but we use floating point)
    note_velocity:
      min_value: 100.0
      step: 5.0
      max_value: 127.0
      default: 127.0
      description: "MIDI velocity (amplitude)"

    # Log10 of decay time in seconds
    log10_decay_time:
      min_value: -1.0 # log10(0.1) = -1.0
      step: 0.1
      max_value: 0.0 # log10(1.0) = 0.0
      default: -0.3 # log10(0.5) = -0.301
      description: "Log10 of exponential decay time constant"

    # Filter enable/disable
    filter_enabled:
      min_value: 1.0 # Always enabled for this test
      max_value: 1.0
      default: 1.0
      description: "Enable Moog VCF filter"

    # Base cutoff frequency
    filter_cutoff:
      min_value: 200.0 # Hz
      step: 100.0
      max_value: 2000.0 # Hz
      default: 800.0
      description: "Filter cutoff frequency in Hz"

    # Filter resonance
    filter_resonance:
      min_value: 0.0
      step: 0.1
      max_value: 0.9 # Keep below 1.0 for stability
      default: 0.5
      description: "Filter resonance (0-1)"

# Configuration references
defaults:
  - /stft: pitch_sync_80
  - /mel: default
  - _self_

# Logging configuration
log_level: DEBUG

# Hydra configuration
hydra:
  run:
    dir: outputs/generate_moog_basic/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: false
