# @package _global_
# High-resonance Moog VCF exploration - Focus on filter self-oscillation and resonant peaks

# Dataset parameters
dataset:
  size: 384 # Good coverage of resonance parameter space
  sampling_rate: 8000 # Sample rate in Hz
  duration: 1.5 # Duration to hear resonant behavior

# Generation parameters
generate:
  batch_size: 8 # Processing batch size
  output_dir: "data" # Base output directory
  pre_emphasis_coefficient: 0.0 # Pre-emphasis filter coefficient (disabled for flat spectrum test)
  taper: false # Taper breath pressure at note ends
  threshold_db: -40 # Audio threshold in dB

  # Output image dimensions
  height: 48 # Taller for better frequency resolution of resonant peaks
  width: 48 # Square aspect for resonance analysis
  channels: 1 # Number of channels (1=grayscale, 3=RGB for derived channels)

# Synthesizer configuration
synthesizer:
  type: simple_saw

  # Parameters that can vary during dataset generation
  parameters:
    # MIDI note number - focus on range where resonance is most audible
    note_number:
      min_value: 40.0 # E2 (82.4 Hz) - guitar low E
      step: 7.0 # Fifth intervals for harmonic interest
      max_value: 54.0 # F#3 (185 Hz)
      default: 47.0 # B2
      description: "MIDI note number (low-mid range for resonance)"

    # MIDI velocity - keep high to hear resonance clearly
    note_velocity:
      min_value: 110.0
      step: 5.0
      max_value: 127.0
      default: 120.0
      description: "MIDI velocity (amplitude)"

    # Decay time - longer to hear resonant behavior
    log10_decay_time:
      min_value: -0.5 # log10(0.316) ≈ -0.5 - ~300ms decay
      step: 0.2
      max_value: 0.5 # log10(3.16) ≈ 0.5 - ~3s decay
      default: 0.0 # log10(1.0) = 0.0 - 1s decay
      description: "Log10 of exponential decay time constant"

    # Filter always enabled
    filter_enabled:
      min_value: 1.0
      max_value: 1.0
      default: 1.0
      description: "Enable Moog VCF filter"

    # Cutoff frequency - explore range where resonance is interesting
    filter_cutoff:
      min_value: 200.0 # Low enough for dramatic filtering
      step: 150.0
      max_value: 1400.0 # High enough for bright tones
      default: 600.0
      description: "Filter cutoff frequency in Hz"

    # Filter resonance - THE KEY PARAMETER - explore high resonance
    filter_resonance:
      min_value: 0.5 # Medium resonance
      step: 0.05 # Fine steps to explore critical region
      max_value: 0.95 # Very high - near self-oscillation
      default: 0.8 # High resonance
      description: "Filter resonance (0-1) - HIGH RANGE"

    # Minimal envelope - let resonance be the star
    filter_env_attack:
      min_value: 0.0
      max_value: 0.01
      default: 0.0
      description: "Filter envelope attack time (seconds) - minimal"

    filter_env_decay:
      min_value: 0.0
      max_value: 0.1
      default: 0.0
      description: "Filter envelope decay time (seconds) - minimal"

    filter_env_sustain:
      min_value: 1.0 # Full sustain - no envelope modulation
      max_value: 1.0
      default: 1.0
      description: "Filter envelope sustain level (0-1) - full"

    filter_env_release:
      min_value: 0.0
      max_value: 0.05
      default: 0.0
      description: "Filter envelope release time (seconds) - minimal"

    filter_env_amount:
      min_value: 0.0 # No envelope modulation - focus on static resonance
      max_value: 0.0
      default: 0.0
      description: "Filter envelope depth (octaves) - disabled"

# Configuration references
defaults:
  - /stft: high_res_256
  - /mel: default
  - _self_

# Logging configuration
log_level: DEBUG

# Hydra configuration
hydra:
  run:
    dir: outputs/generate_moog_resonance/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: false
